---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kopia-ui
resources:
  - namespace.yaml
  - externalsecret.yaml
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
