apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karakeep
resources:
- namespace.yaml
# Chrome resources
- chrome/deployment-chrome.yaml
- chrome/service-chrome.yaml
# karakeep resources
- karakeep/configmap.yaml
- karakeep/deployment-web.yaml
- karakeep/service-web.yaml
- karakeep/externalsecret.yaml
- karakeep/httproute.yaml
- karakeep/pvc-data.yaml
# Meilisearch resources
- meilisearch/deployment-meilisearch.yaml
- meilisearch/service-meilisearch.yaml
- meilisearch/pvc-meilisearch.yaml
