apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni.vanillax.me:8100/
    name: omni-prod-talos-prod-cluster
contexts:
  - context:
      cluster: omni-prod-talos-prod-cluster
      namespace: default
      user: omni-prod-talos-prod-cluster-mitchross09@gmail.com
    name: omni-prod-talos-prod-cluster
current-context: omni-prod-talos-prod-cluster
users:
- name: omni-prod-talos-prod-cluster-mitchross09@gmail.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.vanillax.me/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:talos-prod-cluster
      command: kubectl
      env: null
      provideClusterInfo: false
