---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crunchy-postgres
resources:
  - ns.yaml
  - cluster.yaml
  - externalsecret.yaml
configMapGenerator:
  - name: immich-postgres-init
    files:
      - init.sql=./resources/init.sql
generatorOptions:
  disableNameSuffixHash: true
