apiVersion: v1
kind: Service
metadata:
  name: perplexica
  namespace: perplexica
spec:
  type: ClusterIP
  selector:
    app: perplexica
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
