apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni.vanillax.me:8100/
    name: omni-talos-proxmox
contexts:
  - context:
      cluster: omni-talos-proxmox
      namespace: default
      user: omni-talos-proxmox-mitchross09@gmail.com
    name: omni-talos-proxmox
current-context: omni-talos-proxmox
users:
- name: omni-talos-proxmox-mitchross09@gmail.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.vanillax.me/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:talos-proxmox
      command: kubectl
      env: null
      provideClusterInfo: false
