apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: mailpit
  labels:
    app.kubernetes.io/name: mailpit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mailpit
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Detroit
          ports:
            - name: http
              containerPort: 8025
            - name: smtp
              containerPort: 1025
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
