apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: mailpit
spec:
  ports:
    - name: http
      port: 8025
      targetPort: 8025
      protocol: TCP
    - name: smtp
      port: 1025
      targetPort: 1025
      protocol: TCP
  selector:
    app.kubernetes.io/name: mailpit
