apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - ns.yaml
  - cloudflare-external-secret.yaml

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns
    version: 1.19.0 # renovate: helm=kubernetes-sigs/external-dns
    releaseName: external-dns
    namespace: external-dns
    valuesFile: values.yaml
