apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: copyparty
  labels:
    app: copyparty
    type: config
    backup: "daily"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  # dataSourceRef is added dynamically by Kyverno if a backup exists
