apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty
  namespace: copyparty
  labels:
    app: copyparty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copyparty
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: copyparty
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      containers:
        - name: copyparty
          image: acj21/copyparty:latest
          ports:
            - containerPort: 3923
              name: http
          env:
            - name: PRTY_NO_TLS
              value: "1"
            - name: X_CFG
              value: "/cfg/copyparty.conf"
          volumeMounts:
            - name: media
              mountPath: /w/media
            - name: config
              mountPath: /cfg
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: copyparty-media
        - name: config
          persistentVolumeClaim:
            claimName: copyparty-config-pvc
