apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - media-pvc.yaml
  - config-pvc.yaml
  - deployment.yaml
  - svc.yaml
  - httproute.yaml

configMapGenerator:
  - name: copyparty-config
    files:
      - copyparty.conf
