apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: copyparty

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ns.yaml
  - data-pvc.yaml
  - deployment.yaml
  - svc.yaml
  - httproute.yaml

configMapGenerator:
  - name: copyparty-config
    files:
      - copyparty.conf
