apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-configuration
  namespace: karakeep
data:
  # Add any non-secret configuration values here
  NEXTAUTH_URL: "https://karakeep.vanillax.me"
  # OLLAMA_BASE_URL: "https://ollama.vanillax.me/api"
  OPENAI_BASE_URL: "http://llama-cpp-service.llama-cpp.svc.cluster.local:8080/v1"
  OPENAI_API_KEY: "sk-required"
  OLLAMA_KEEP_ALIVE: "5m"
  INFERENCE_TEXT_MODEL: "coder - qwen3-coder-next"
  INFERENCE_IMAGE_MODEL: "vision - qwen3-vl-thinking"
  EMBEDDING_TEXT_MODEL: "granite-embedding:278m"
  # For webhook functionality (new in 0.22.0)
  WEBHOOK_ENABLED: "false"
  # Add any other configuration values as needed
  DISABLE_SIGNUPS: "false"
  # Crawler settings
  CRAWLER_ENABLE_ADBLOCKER: "true"
  CRAWLER_JOB_TIMEOUT_SEC: "60"
  # OCR settings
  OCR_LANGS: "eng"
