apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
        app.kubernetes.io/component: server
    spec:
      containers:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:v2.3.1@sha256:f8d06a32b1b2a81053d78e40bf8e35236b9faefb5c3903ce9ca8712c9ed78445
        ports:
        - name: http
          containerPort: 2283
          protocol: TCP
        - name: metrics-api
          containerPort: 8081
          protocol: TCP
        - name: metrics-ms
          containerPort: 8082
          protocol: TCP
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: IMMICH_TRUSTED_PROXIES
          value: "172.31.0.0/16"
        - name: IMMICH_MEDIA_LOCATION
          value: /library
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: immich-db-user-secret
              key: uri
        - name: REDIS_HOSTNAME
          value: "immich-valkey.immich.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: IMMICH_PORT
          value: "2283"
        - name: IMMICH_MACHINE_LEARNING_URL
          value: "http://immich-machine-learning.immich.svc.cluster.local:3003"
        - name: IMMICH_TELEMETRY_INCLUDE
          value: "all"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 6Gi
        volumeMounts:
        - name: library
          mountPath: /library
        - name: geocoding
          mountPath: /usr/src/app/.reverse-geocoding-dump
        - name: transformers
          mountPath: /usr/src/app/.transformers_cache
      volumes:
      - name: library
        persistentVolumeClaim:
          claimName: immich-library
      - name: geocoding
        emptyDir: {}
      - name: transformers
        emptyDir: {}
