apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- ns.yaml
- minio.yaml
helmCharts:
- name: tempo
  repo: https://grafana.github.io/helm-charts
  version: 1.24.1 # Latest
  releaseName: tempo
  valuesFile: values.yaml
