apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- ns.yaml
- externalsecret.yaml
# Removed minio.yaml - using external S3 (TrueNAS RustFS)
helmCharts:
- name: tempo
  repo: https://grafana.github.io/helm-charts
  version: 1.24.3 # Latest
  releaseName: tempo
  valuesFile: values.yaml
