apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync-system
resources:
  - namespace.yaml
  - externalsecret.yaml
  - sync-cronjob.yaml
helmCharts:
  - name: volsync
    repo: https://backube.github.io/helm-charts
    version: 0.11.0
    releaseName: volsync
    namespace: volsync-system
    valuesFile: values.yaml
    includeCRDs: true
