apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
resources:
  - ns.yaml
helmCharts:
  - name: pgo
    repo: oci://registry.developers.crunchydata.com/crunchydata
    version: 5.8.5
    releaseName: pgo
    namespace: postgres-operator
    valuesFile: values.yaml
    includeCRDs: true
