apiVersion: apps/v1
kind: Deployment
metadata:
  name: vert
  namespace: vert
  labels:
    app.kubernetes.io/name: vert
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vert
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vert
    spec:
      containers:
        - name: vert
          image: ghcr.io/vert-sh/vert:latest@sha256:ac1bafe627c72f6dcb3a03357a455be58913e51fa6fc822dbc5ba7b6b842c134
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PUB_ENV
              value: "production"
            - name: PUB_HOSTNAME
              value: "vert.vanillax.me"
            # Optional: Configure vertd URL for video conversion
            # - name: PUB_VERTD_URL
            #   value: "http://vertd.development.svc.cluster.local:24153"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
